# ============================================================
# PROJECT      : BRANDPILOT — AI Brand Scaling Tool
# FILE         : alembic/versions/0003_campaign_agent_social_posts_validations_metrics.py
# DESCRIPTION  : Campaign Agent schema —
#                  ALTER  campaigns (source, prompt_original, intent_parsed, status)
#                  CREATE social_posts
#                  CREATE campaign_validations
#                  CREATE campaign_suggestions
#                  CREATE social_metrics
# AUTHOR       : BRANDPILOT Dev Team
# LAST UPDATED : 2026-03-10
# ============================================================
"""Campaign Agent: social_posts, validations, suggestions, metrics

Revision ID: 0003
Revises: 0002
Create Date: 2026-03-10 12:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# ---------------------------------------------------------------------------
# Revision identifiers — used by Alembic.
# ---------------------------------------------------------------------------
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# upgrade
# ---------------------------------------------------------------------------

def upgrade() -> None:

    # ------------------------------------------------------------------
    # campaigns — Campaign Agent tracking columns + status check constraint
    #
    # op.batch_alter_table is used for ALTER TABLE so the migration also
    # runs cleanly against SQLite in the local dev / test environment.
    # ------------------------------------------------------------------
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source",
                sa.String(20),
                nullable=False,
                server_default="manual",
                comment="Campaign origin: 'manual' (created in UI) or 'agent' (AI-generated)",
            )
        )
        batch_op.add_column(
            sa.Column(
                "prompt_original",
                sa.Text,
                nullable=True,
                comment="Raw natural-language brief submitted by the user to the Campaign Agent",
            )
        )
        batch_op.add_column(
            sa.Column(
                "intent_parsed",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=True,
                comment="Structured CampaignIntent JSON extracted from the prompt",
            )
        )
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(30),
                nullable=False,
                server_default="pending_validation",
                comment="Agent pipeline status (HITL gate)",
            )
        )
        # CHECK constraint — valid values mirror CampaignStatus enum
        batch_op.create_check_constraint(
            "chk_campaign_status",
            sa.text(
                "status IN ("
                "'pending_validation','approved','active',"
                "'completed','cancelled','failed'"
                ")"
            ),
        )

    # ------------------------------------------------------------------
    # social_posts — one row per scheduled / published social media post
    # ------------------------------------------------------------------
    op.create_table(
        "social_posts",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
            comment="Post UUID (generated by PostgreSQL)",
        ),
        sa.Column(
            "campaign_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("campaigns.id", ondelete="CASCADE"),
            nullable=False,
            comment="Parent campaign",
        ),
        sa.Column(
            "platform",
            sa.String(20),
            nullable=False,
            comment="Target platform: instagram|tiktok|youtube|x|linkedin|facebook",
        ),
        sa.Column(
            "content_text",
            sa.Text,
            nullable=True,
            comment="Post caption or body copy",
        ),
        sa.Column(
            "media_urls",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
            comment="Ordered list of media asset URLs",
        ),
        sa.Column(
            "hashtags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
            comment="List of hashtag strings (without leading #)",
        ),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC datetime when Celery Beat must publish this post",
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC datetime the post was actually published (NULL = not yet)",
        ),
        sa.Column(
            "status",
            sa.String(30),
            nullable=False,
            server_default="pending_validation",
            comment="HITL status: pending_validation|approved|scheduled|published|failed",
        ),
        sa.Column(
            "platform_post_id",
            sa.String(200),
            nullable=True,
            comment="ID returned by the social platform API after publishing",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Updated by application layer on every write",
        ),
    )
    # Composite index — used by Campaign Agent status queries
    op.create_index(
        "idx_social_posts_campaign_status",
        "social_posts",
        ["campaign_id", "status"],
    )
    # Single-column index — used by Celery Beat to look up due posts
    op.create_index(
        "idx_social_posts_scheduled_at",
        "social_posts",
        ["scheduled_at"],
    )

    # ------------------------------------------------------------------
    # campaign_validations — immutable HITL audit trail
    # ------------------------------------------------------------------
    op.create_table(
        "campaign_validations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "campaign_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("campaigns.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
            comment="User who performed the validation action",
        ),
        sa.Column(
            "action",
            sa.String(20),
            nullable=False,
            comment="Validation action: 'approved'|'rejected'|'modified'",
        ),
        sa.Column(
            "modified_posts",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Snapshot of posts that were modified (NULL when action != modified)",
        ),
        sa.Column(
            "validated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # ------------------------------------------------------------------
    # campaign_suggestions — AI-generated improvement hints shown in ValidationBoard
    # ------------------------------------------------------------------
    op.create_table(
        "campaign_suggestions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "campaign_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("campaigns.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "suggestion_type",
            sa.String(50),
            nullable=False,
            comment="Category: 'hashtag'|'timing'|'caption'|'influencer'|'budget'…",
        ),
        sa.Column(
            "suggestion_text",
            sa.Text,
            nullable=False,
            comment="Human-readable suggestion body",
        ),
        sa.Column(
            "applied",
            sa.Boolean,
            nullable=False,
            server_default=sa.false(),
            comment="True once the user has applied this suggestion",
        ),
        sa.Column(
            "user_decision",
            sa.String(20),
            nullable=False,
            server_default="pending",
            comment="User decision: 'pending'|'accepted'|'dismissed'",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )

    # ------------------------------------------------------------------
    # social_metrics — post-level analytics collected T+24 h via Celery
    # ------------------------------------------------------------------
    op.create_table(
        "social_metrics",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "post_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("social_posts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "platform",
            sa.String(20),
            nullable=False,
            comment="Denormalized platform for partition-friendly queries",
        ),
        sa.Column("impressions", sa.Integer, nullable=True),
        sa.Column("reach", sa.Integer, nullable=True),
        sa.Column("likes", sa.Integer, nullable=True),
        sa.Column("comments", sa.Integer, nullable=True),
        sa.Column("shares", sa.Integer, nullable=True),
        sa.Column("clicks", sa.Integer, nullable=True),
        sa.Column(
            "engagement_rate",
            sa.Numeric(5, 2),
            nullable=True,
            comment="Percentage: (likes+comments+shares) / reach × 100",
        ),
        sa.Column("followers_gained", sa.Integer, nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="UTC datetime the metrics snapshot was fetched from the platform API",
        ),
    )


# ---------------------------------------------------------------------------
# downgrade — tables and columns dropped in strict reverse-dependency order
# ---------------------------------------------------------------------------

def downgrade() -> None:

    # social_metrics references social_posts → drop first
    op.drop_table("social_metrics")

    # campaign_suggestions and campaign_validations reference campaigns only
    op.drop_table("campaign_suggestions")
    op.drop_table("campaign_validations")

    # Drop social_posts indexes before dropping the table
    op.drop_index("idx_social_posts_scheduled_at", table_name="social_posts")
    op.drop_index("idx_social_posts_campaign_status", table_name="social_posts")
    op.drop_table("social_posts")

    # Remove columns and CHECK constraint added to campaigns
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_constraint("chk_campaign_status", type_="check")
        batch_op.drop_column("status")
        batch_op.drop_column("intent_parsed")
        batch_op.drop_column("prompt_original")
        batch_op.drop_column("source")
