# -*- coding: utf-8 -*-
# BRANDPILOT — microservices/campaign_agent/agent.py
# CampaignAgent: orchestrateur central du pipeline campagne en 10 étapes.
# Copyright © 2026 BRANDPILOT Dev Team — MIT License

from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime, timedelta
from typing import Any, Protocol, runtime_checkable

import redis.asyncio as aioredis
from celery import Celery, chord, group
from loguru import logger
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from backend.exceptions import BrandpilotError
from configs.settings import get_settings
from database.models_orm import Campaign, CampaignStatus, Project, WorkflowJob
from microservices.campaign_agent.intent_parser import CampaignIntent, parse_intent

# ---------------------------------------------------------------------------
# Agent-specific exceptions
# ---------------------------------------------------------------------------


class CampaignNotFoundError(BrandpilotError):
    """Raised when a campaign_id does not exist in the database."""

    def __init__(self, campaign_id: str) -> None:
        super().__init__(
            message=f"Campaign '{campaign_id}' not found.",
            code="CAMPAIGN_NOT_FOUND",
        )


class InvalidStatusError(BrandpilotError):
    """Raised when an operation is invalid for the campaign's current status.

    Attributes:
        current_status: The actual status found in the DB.
        expected_status: The status required by the operation.
    """

    def __init__(self, current_status: str, expected_status: str) -> None:
        super().__init__(
            message=(
                f"Cannot perform operation: campaign is '{current_status}', "
                f"expected '{expected_status}'."
            ),
            code="INVALID_STATUS",
        )
        self.current_status = current_status
        self.expected_status = expected_status


class UnauthorizedError(BrandpilotError):
    """Raised when the requesting user does not own the campaign."""

    def __init__(self, campaign_id: str, user_id: str) -> None:
        super().__init__(
            message=(
                f"User '{user_id}' is not authorized to modify campaign "
                f"'{campaign_id}'."
            ),
            code="UNAUTHORIZED",
        )


# ---------------------------------------------------------------------------
# In-memory data models
# (SocialPost and CampaignValidation require Alembic migration to persist
#  as first-class tables; until then, they are stored in WorkflowJob.result)
# ---------------------------------------------------------------------------


@dataclass
class SocialPost:
    """A single scheduled social media post generated by the Campaign Agent.

    Attributes:
        id:               UUID of this post.
        campaign_id:      Parent campaign UUID.
        platform:         Target social platform (instagram, tiktok, …).
        content_text:     Generated caption / body text.
        media_urls:       List of S3 media asset URLs.
        hashtags:         Suggested hashtags.
        scheduled_at:     UTC datetime when the post should go live.
        status:           Lifecycle state of the post.
        platform_post_id: ID returned by the social API after publishing.
        published_at:     UTC datetime when the post was actually published.
        celery_task_id:   Celery ETA task ID for revocation on cancel.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    campaign_id: str = ""
    platform: str = ""
    content_text: str = ""
    media_urls: list[str] = field(default_factory=list)
    hashtags: list[str] = field(default_factory=list)
    scheduled_at: str = ""  # ISO-8601 UTC string
    status: str = "draft"  # draft|pending_validation|approved|scheduled|published|failed|cancelled
    platform_post_id: str | None = None
    published_at: str | None = None
    celery_task_id: str | None = None


@dataclass
class CampaignValidationRecord:
    """Audit trail entry for a campaign approval / rejection action.

    Attributes:
        id:             UUID of this record.
        campaign_id:    Campaign being validated.
        user_id:        User who performed the action.
        action:         "approved" | "rejected" | "modified".
        modified_posts: JSONB snapshot of any modified posts.
        validated_at:   UTC ISO-8601 timestamp.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    campaign_id: str = ""
    user_id: str = ""
    action: str = "approved"
    modified_posts: list[dict[str, Any]] = field(default_factory=list)
    validated_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat()
    )


@dataclass
class BrandContext:
    """Brand and account context loaded from the database.

    Attributes:
        project_id:       UUID of the project.
        brand_name:       Display name of the brand.
        brand_tone:       Detected brand tone (energetic / professional / …).
        social_accounts:  List of connected platform account IDs.
        target_audience:  Free-form audience description from brand analysis.
    """

    project_id: str
    brand_name: str = ""
    brand_tone: str = "professional"
    social_accounts: list[str] = field(default_factory=list)
    target_audience: str = ""


@dataclass
class ExecutionPlan:
    """Microservice routing plan produced by the execution planner.

    Attributes:
        microservices: Ordered list of microservice names to invoke.
        parallel_tasks: Names of tasks that can run concurrently in the chord.
        estimated_duration_s: Rough wall-clock estimate in seconds.
    """

    microservices: list[str]
    parallel_tasks: list[str]
    estimated_duration_s: int = 30


# ---------------------------------------------------------------------------
# Dependency injection protocols
# ---------------------------------------------------------------------------


@runtime_checkable
class IntentParserProtocol(Protocol):
    """Interface for the intent parsing dependency."""

    async def parse(self, prompt: str) -> CampaignIntent:
        """Parse a natural-language prompt into a CampaignIntent."""
        ...


@runtime_checkable
class ContextBuilderProtocol(Protocol):
    """Interface for the brand context loading dependency."""

    async def build(self, project_id: str) -> BrandContext:
        """Load and return the BrandContext for a given project."""
        ...


# ---------------------------------------------------------------------------
# Redis pub/sub helper
# ---------------------------------------------------------------------------

_REDIS_CHANNEL_PREFIX = "campaign:event"


async def _publish_event(event: str, payload: dict[str, Any]) -> None:
    """Publish a campaign lifecycle event to Redis pub/sub.

    Frontend subscribers (WebSocket gateway) listen on these channels to
    push real-time updates without polling.

    Args:
        event:   Event name, e.g. ``"campaign.ready"``.
        payload: Arbitrary JSON-serialisable dict.
    """
    settings = get_settings()
    try:
        async with aioredis.from_url(settings.redis_url) as redis:
            channel = f"{_REDIS_CHANNEL_PREFIX}:{event}"
            await redis.publish(channel, json.dumps(payload))
            logger.debug(
                "[CampaignAgent] Event published | channel={} payload={}",
                channel,
                payload,
            )
    except Exception as exc:  # pragma: no cover
        # Notification failure must never abort the main pipeline.
        logger.warning(
            "[CampaignAgent] Redis publish failed (non-fatal) | event={} error={}",
            event,
            exc,
        )


# ---------------------------------------------------------------------------
# Internal DB helpers
# ---------------------------------------------------------------------------


async def _load_campaign_with_owner(
    db: AsyncSession,
    campaign_id: str,
) -> tuple[Campaign, str]:
    """Load a Campaign and resolve its owner user_id via Project join.

    Args:
        db:          Async database session.
        campaign_id: String UUID of the campaign.

    Returns:
        Tuple of (Campaign ORM instance, owner user_id string).

    Raises:
        CampaignNotFoundError: Campaign does not exist.
    """
    stmt = (
        select(Campaign, Project.user_id)
        .join(Project, Campaign.project_id == Project.id)
        .where(Campaign.id == uuid.UUID(campaign_id))
    )
    result = await db.execute(stmt)
    row = result.first()
    if row is None:
        raise CampaignNotFoundError(campaign_id)
    campaign, owner_id = row
    return campaign, str(owner_id)


async def _load_agent_job(
    db: AsyncSession,
    campaign_id: str,
) -> WorkflowJob | None:
    """Return the WorkflowJob associated with a campaign agent run.

    Args:
        db:          Async database session.
        campaign_id: String UUID of the campaign.

    Returns:
        Most-recent matching WorkflowJob or None.
    """
    result = await db.execute(
        select(WorkflowJob)
        .where(WorkflowJob.campaign_id == uuid.UUID(campaign_id))
        .where(WorkflowJob.job_type == "campaign_agent")
        .order_by(WorkflowJob.created_at.desc())
        .limit(1)
    )
    return result.scalar_one_or_none()


def _posts_from_job(job: WorkflowJob) -> list[SocialPost]:
    """Deserialise SocialPost list from a WorkflowJob result payload.

    Args:
        job: WorkflowJob whose ``result`` contains serialised posts.

    Returns:
        List of SocialPost instances (empty if none stored yet).
    """
    if not job.result:
        return []
    raw_posts: list[dict[str, Any]] = job.result.get("posts", [])
    return [SocialPost(**p) for p in raw_posts]


# ---------------------------------------------------------------------------
# CampaignAgent
# ---------------------------------------------------------------------------


class CampaignAgent:
    """Orchestrates the full 10-step campaign generation pipeline.

    Responsibilities:
      1. Parse intent from a natural-language prompt.
      2. Load brand context and social accounts from the database.
      3. Plan which microservices to invoke.
      4. Launch parallel Celery chord (brand analysis, audience, influencers).
      5. Persist campaign with status ``pending_validation``.
      6. Notify the frontend via Redis pub/sub.

    Post-generation:
      - ``approve_and_schedule`` — human-in-the-loop approval gate.
      - ``reject_and_regenerate`` — regenerate a single post with feedback.
      - ``cancel_campaign`` — revoke all pending Celery ETA tasks.

    Security invariant:
      ⛔ Status can ONLY transition to ``scheduled`` or ``published`` inside
      ``worker.publish_post_at_scheduled_time()``, never here.

    Args:
        db:              Injected async SQLAlchemy session.
        celery_app:      Injected Celery application instance.
        intent_parser:   Injected intent parser (default: module-level parse_intent).
        context_builder: Injected context builder.
    """

    def __init__(
        self,
        db: AsyncSession,
        celery_app: Celery,
        intent_parser: IntentParserProtocol | None = None,
        context_builder: ContextBuilderProtocol | None = None,
    ) -> None:
        self._db = db
        self._celery = celery_app
        self._intent_parser = intent_parser
        self._context_builder = context_builder

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def build_campaign(
        self,
        prompt: str,
        project_id: str,
        user_id: str,
    ) -> str:
        """Run the full 10-step campaign generation pipeline from a single prompt.

        Args:
            prompt:     Natural-language campaign brief from the user.
            project_id: UUID of the owning project.
            user_id:    UUID of the requesting user (for audit trail).

        Returns:
            campaign_id (str UUID) of the newly created campaign.

        Raises:
            AmbiguousPromptError: The prompt is too vague (< 3 fields).
            IntentParseError:     GPT-4 returned malformed JSON.
            OpenAITimeoutError:   GPT-4 API call timed out.
        """
        logger.info(
            "[CampaignAgent] build_campaign | project={} user={} prompt={!r}",
            project_id,
            user_id,
            prompt[:80],
        )
        campaign_id = await self._run_pipeline_steps(prompt, project_id)
        await _publish_event(
            "campaign.ready",
            {
                "campaign_id": campaign_id,
                "project_id": project_id,
                "user_id": user_id,
                "status": "pending_validation",
            },
        )
        logger.success(
            "[CampaignAgent] Campaign ready | id={} status=pending_validation",
            campaign_id,
        )
        return campaign_id

    async def _run_pipeline_steps(
        self,
        prompt: str,
        project_id: str,
    ) -> str:
        """Execute pipeline steps 1-8 and return the campaign_id.

        Separated from ``build_campaign`` to keep each method ≤ 50 lines.

        Args:
            prompt:     Raw user prompt.
            project_id: UUID of the owning project.

        Returns:
            campaign_id (str UUID).
        """
        intent = await self._step_parse_intent(prompt)
        context = await self._step_build_context(project_id)
        campaign_id = await self._step_persist_campaign(
            project_id=project_id,
            intent=intent,
        )
        job_id = await self._step_persist_workflow_job(campaign_id, intent, context)
        self._step_launch_chord(campaign_id, project_id, job_id, intent)
        return campaign_id

    async def approve_and_schedule(
        self,
        campaign_id: str,
        user_id: str,
    ) -> bool:
        """Approve a campaign and schedule all posts via Celery ETA tasks.

        Human-in-the-loop gate: verifies ownership and status before
        any scheduling action is taken.

        Args:
            campaign_id: UUID of the campaign to approve.
            user_id:     UUID of the approving user.

        Returns:
            True on success.

        Raises:
            CampaignNotFoundError: Campaign does not exist.
            UnauthorizedError:     Requesting user is not the owner.
            InvalidStatusError:    Campaign is not in ``pending_validation``.
        """
        campaign, owner_id = await _load_campaign_with_owner(self._db, campaign_id)
        self._assert_ownership(campaign_id, user_id, owner_id)

        job = await _load_agent_job(self._db, campaign_id)
        agent_status = (job.result or {}).get("agent_status", "draft") if job else "draft"
        self._assert_pending_validation(agent_status, campaign_id)

        posts = _posts_from_job(job) if job else []
        task_ids = self._schedule_posts(posts)
        await self._persist_approval(campaign, job, posts, task_ids, user_id)

        logger.success(
            "[CampaignAgent] Campaign approved | id={} posts_scheduled={}",
            campaign_id,
            len(task_ids),
        )
        await _publish_event(
            "campaign.approved",
            {"campaign_id": campaign_id, "user_id": user_id},
        )
        return True

    async def reject_and_regenerate(
        self,
        campaign_id: str,
        post_id: str,
        feedback: str,
        user_id: str,
    ) -> SocialPost:
        """Regenerate a single post with user feedback.

        The overall campaign status does NOT change — only this post is
        sent back to the AI text service for regeneration.

        Args:
            campaign_id: UUID of the parent campaign.
            post_id:     UUID of the post to regenerate.
            feedback:    Free-form user feedback for the regeneration prompt.
            user_id:     UUID of the requesting user (ownership check).

        Returns:
            Updated SocialPost with status ``pending_validation``.

        Raises:
            CampaignNotFoundError: Campaign does not exist.
            UnauthorizedError:     Requesting user is not the owner.
        """
        _, owner_id = await _load_campaign_with_owner(self._db, campaign_id)
        self._assert_ownership(campaign_id, user_id, owner_id)

        task = self._celery.send_task(
            "bs_ai_text.regenerate_post",
            args=[post_id, feedback, campaign_id],
        )
        logger.info(
            "[CampaignAgent] Post regeneration queued | campaign={} post={} task={}",
            campaign_id,
            post_id,
            task.id,
        )

        return SocialPost(
            id=post_id,
            campaign_id=campaign_id,
            status="pending_validation",
            celery_task_id=task.id,
        )

    async def cancel_campaign(
        self,
        campaign_id: str,
        user_id: str,
    ) -> bool:
        """Cancel a campaign and revoke all future Celery ETA tasks.

        Tasks scheduled more than 5 minutes in the future are revoked.
        Already-published posts are left intact (immutable audit trail).

        Args:
            campaign_id: UUID of the campaign to cancel.
            user_id:     UUID of the requesting user.

        Returns:
            True on success.

        Raises:
            CampaignNotFoundError: Campaign does not exist.
            UnauthorizedError:     Requesting user is not the owner.
        """
        campaign, owner_id = await _load_campaign_with_owner(self._db, campaign_id)
        self._assert_ownership(campaign_id, user_id, owner_id)

        job = await _load_agent_job(self._db, campaign_id)
        posts = _posts_from_job(job) if job else []
        revoked = self._revoke_future_tasks(posts)

        await self._persist_cancellation(campaign, job, posts)

        logger.warning(
            "[CampaignAgent] Campaign cancelled | id={} revoked_tasks={}",
            campaign_id,
            revoked,
        )
        await _publish_event(
            "campaign.cancelled",
            {"campaign_id": campaign_id, "user_id": user_id, "revoked_tasks": revoked},
        )
        return True

    # ------------------------------------------------------------------
    # Pipeline steps (private)
    # ------------------------------------------------------------------

    async def _step_parse_intent(self, prompt: str) -> CampaignIntent:
        """Step 1 — parse the user prompt into a structured CampaignIntent.

        Uses the injected parser if provided, otherwise falls back to the
        module-level ``parse_intent`` coroutine.

        Args:
            prompt: Raw natural-language campaign brief.

        Returns:
            Parsed CampaignIntent.
        """
        if self._intent_parser is not None:
            return await self._intent_parser.parse(prompt)
        return await parse_intent(prompt)

    async def _step_build_context(self, project_id: str) -> BrandContext:
        """Step 2 — load brand context and connected social accounts from DB.

        Args:
            project_id: UUID of the owning project.

        Returns:
            BrandContext with brand metadata.
        """
        if self._context_builder is not None:
            return await self._context_builder.build(project_id)

        # Minimal fallback: load project name from DB.
        result = await self._db.execute(
            select(Project).where(Project.id == uuid.UUID(project_id))
        )
        project = result.scalar_one_or_none()
        brand_name = project.name if project else "BRANDPILOT Brand"
        logger.debug(
            "[CampaignAgent] Context loaded (minimal) | project={} brand={}",
            project_id,
            brand_name,
        )
        return BrandContext(project_id=project_id, brand_name=brand_name)

    async def _step_persist_campaign(
        self,
        project_id: str,
        intent: CampaignIntent,
    ) -> str:
        """Step 5 — persist a Campaign row with status=draft.

        The campaign is created as ``draft`` in the existing CampaignStatus
        enum.  The agent-specific ``pending_validation`` state is tracked
        inside the companion WorkflowJob.result JSONB.

        Args:
            project_id: UUID of the owning project.
            intent:     Parsed campaign intent.

        Returns:
            campaign_id (str UUID).
        """
        campaign = Campaign(
            project_id=uuid.UUID(project_id),
            name=_campaign_name(intent),
            status=CampaignStatus.draft,
            channel="social",  # type: ignore[arg-type]
        )
        self._db.add(campaign)
        await self._db.flush()
        await self._db.refresh(campaign)
        campaign_id = str(campaign.id)
        logger.info(
            "[CampaignAgent] Campaign persisted | id={} name={}",
            campaign_id,
            campaign.name,
        )
        return campaign_id

    async def _step_persist_workflow_job(
        self,
        campaign_id: str,
        intent: CampaignIntent,
        context: BrandContext,
    ) -> str:
        """Persist a WorkflowJob to track agent pipeline state.

        Args:
            campaign_id: UUID of the campaign.
            intent:      Parsed intent (stored in payload).
            context:     Brand context (stored in payload).

        Returns:
            job_id (str UUID).
        """
        now = datetime.now(UTC)
        job = WorkflowJob(
            campaign_id=uuid.UUID(campaign_id),
            job_type="campaign_agent",
            status="pending",  # type: ignore[arg-type]
            payload={
                "intent": asdict(intent),
                "brand_context": asdict(context),
            },
            result={"agent_status": "pending_validation", "posts": []},
            started_at=now,
        )
        self._db.add(job)
        await self._db.flush()
        await self._db.refresh(job)
        job_id = str(job.id)
        logger.debug("[CampaignAgent] WorkflowJob created | id={}", job_id)
        return job_id

    def _step_launch_chord(
        self,
        campaign_id: str,
        project_id: str,
        job_id: str,
        intent: CampaignIntent,
    ) -> None:
        """Step 4 — dispatch the Celery chord for parallel brand/audience analysis.

        ⛔ The callback status is hard-coded to ``"pending_validation"`` —
        it may NEVER be overridden to ``"scheduled"`` or ``"published"``.

        Args:
            campaign_id: UUID of the campaign.
            project_id:  UUID of the project.
            job_id:      UUID of the tracking WorkflowJob.
            intent:      Parsed campaign intent.
        """
        header = self._build_chord_header(project_id, intent)
        callback = self._build_chord_callback(campaign_id, project_id, job_id, intent)
        chord(header, callback).delay()
        logger.info(
            "[CampaignAgent] Chord dispatched | campaign={} tasks=3+callback",
            campaign_id,
        )

    def _build_chord_header(
        self,
        project_id: str,
        intent: CampaignIntent,
    ) -> Any:
        """Build the parallel group of three analysis tasks.

        Args:
            project_id: UUID of the project (for brand analysis).
            intent:     Parsed intent (for audience/influencer tasks).

        Returns:
            Celery group of three signatures.
        """
        sig = self._celery.signature
        return group([
            sig("campaign_agent.analyze_brand", args=[project_id]),
            sig(
                "campaign_agent.analyze_audience",
                args=[intent.platform, intent.audience_age, intent.audience_gender],
            ),
            sig(
                "campaign_agent.suggest_influencers",
                args=[intent.budget_influencer, intent.platform],
            ),
        ])

    def _build_chord_callback(
        self,
        campaign_id: str,
        project_id: str,
        job_id: str,
        intent: CampaignIntent,
    ) -> Any:
        """Build the chord callback signature that assembles the campaign plan.

        Args:
            campaign_id: UUID of the campaign.
            project_id:  UUID of the project.
            job_id:      UUID of the tracking WorkflowJob.
            intent:      Parsed intent serialised as dict for the worker.

        Returns:
            Celery signature for ``build_campaign_plan``.
        """
        return self._celery.signature(
            "campaign_agent.build_campaign_plan",
            kwargs={
                "campaign_id": campaign_id,
                "project_id": project_id,
                "job_id": job_id,
                "intent_dict": asdict(intent),
                "status": "pending_validation",  # IMMUTABLE — never change this
            },
        )

    # ------------------------------------------------------------------
    # Approve helpers (private)
    # ------------------------------------------------------------------

    def _schedule_posts(self, posts: list[SocialPost]) -> list[str]:
        """Send one Celery ETA task per approved post.

        Args:
            posts: SocialPost instances to schedule.

        Returns:
            List of Celery task IDs.
        """
        task_ids: list[str] = []
        for post in posts:
            if post.status in ("published", "cancelled", "failed"):
                continue
            scheduled_at = datetime.fromisoformat(post.scheduled_at) if post.scheduled_at else datetime.now(UTC) + timedelta(hours=1)
            task = self._celery.send_task(
                "publish_post_at_scheduled_time",
                args=[post.id],
                eta=scheduled_at,
            )
            post.celery_task_id = task.id
            post.status = "scheduled"
            task_ids.append(task.id)
            logger.debug(
                "[CampaignAgent] Post scheduled | post={} eta={} task={}",
                post.id,
                scheduled_at.isoformat(),
                task.id,
            )
        return task_ids

    async def _persist_approval(
        self,
        campaign: Campaign,
        job: WorkflowJob | None,
        posts: list[SocialPost],
        task_ids: list[str],
        user_id: str,
    ) -> None:
        """Persist approval: update Campaign status + WorkflowJob result + audit record.

        Args:
            campaign:  ORM campaign to mark active.
            job:       Agent WorkflowJob to update with new post states.
            posts:     Updated SocialPost list with Celery task IDs.
            task_ids:  Celery task IDs from scheduling.
            user_id:   Approving user UUID.
        """
        campaign.status = CampaignStatus.active
        campaign.launched_at = datetime.now(UTC)

        if job is not None:
            job.result = {
                "agent_status": "approved",
                "posts": [asdict(p) for p in posts],
                "task_ids": task_ids,
            }
            job.status = "completed"  # type: ignore[assignment]
            job.completed_at = datetime.now(UTC)

        validation = CampaignValidationRecord(
            campaign_id=str(campaign.id),
            user_id=user_id,
            action="approved",
        )
        # Store audit record in job payload until CampaignValidation ORM is migrated.
        if job is not None and job.payload is not None:
            job.payload["validation"] = asdict(validation)

        await self._db.flush()

    # ------------------------------------------------------------------
    # Cancel helpers (private)
    # ------------------------------------------------------------------

    def _revoke_future_tasks(self, posts: list[SocialPost]) -> int:
        """Revoke Celery ETA tasks scheduled more than 5 minutes in the future.

        Args:
            posts: SocialPost list; each may carry a ``celery_task_id``.

        Returns:
            Number of tasks successfully revoked.
        """
        horizon = datetime.now(UTC) + timedelta(minutes=5)
        revoked = 0
        for post in posts:
            if post.status in ("published", "failed"):
                continue
            if not post.celery_task_id:
                continue
            eta = datetime.fromisoformat(post.scheduled_at) if post.scheduled_at else None
            if eta is None or eta > horizon:
                self._celery.control.revoke(
                    post.celery_task_id,
                    terminate=True,
                    signal="SIGTERM",
                )
                post.status = "cancelled"
                revoked += 1
        return revoked

    async def _persist_cancellation(
        self,
        campaign: Campaign,
        job: WorkflowJob | None,
        posts: list[SocialPost],
    ) -> None:
        """Mark campaign and all non-published posts as cancelled.

        Args:
            campaign: ORM Campaign to update.
            job:      Agent WorkflowJob to update.
            posts:    SocialPost list to mark cancelled.
        """
        campaign.status = CampaignStatus.paused  # closest existing enum value

        if job is not None:
            job.status = "failed"  # type: ignore[assignment]
            job.result = {
                "agent_status": "cancelled",
                "posts": [asdict(p) for p in posts],
            }
            job.completed_at = datetime.now(UTC)

        await self._db.flush()

    # ------------------------------------------------------------------
    # Guard helpers (private)
    # ------------------------------------------------------------------

    @staticmethod
    def _assert_ownership(
        campaign_id: str,
        requesting_user_id: str,
        owner_user_id: str,
    ) -> None:
        """Raise UnauthorizedError if the user does not own the campaign.

        Args:
            campaign_id:        Campaign UUID (for error message).
            requesting_user_id: User making the request.
            owner_user_id:      Actual owner resolved from DB.

        Raises:
            UnauthorizedError: Requesting user is not the owner.
        """
        if requesting_user_id != owner_user_id:
            raise UnauthorizedError(campaign_id, requesting_user_id)

    @staticmethod
    def _assert_pending_validation(
        agent_status: str,
        campaign_id: str,
    ) -> None:
        """Raise InvalidStatusError if the campaign is not pending validation.

        Args:
            agent_status: Current agent status from WorkflowJob.result.
            campaign_id:  Campaign UUID (for error message only).

        Raises:
            InvalidStatusError: Status is not ``pending_validation``.
        """
        if agent_status != "pending_validation":
            raise InvalidStatusError(
                current_status=agent_status,
                expected_status="pending_validation",
            )


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------


def _campaign_name(intent: CampaignIntent) -> str:
    """Build a human-readable default campaign name from the intent.

    Args:
        intent: Parsed CampaignIntent.

    Returns:
        A short descriptive name string.

    Example:
        >>> _campaign_name(CampaignIntent(platform="instagram", objective="awareness"))
        'instagram — awareness'
    """
    parts: list[str] = [intent.platform, intent.objective]
    if intent.product_description:
        # Keep it concise: first 30 chars of the product description.
        parts.append(intent.product_description[:30])
    return " — ".join(parts)
