#!/usr/bin/env python3
"""
generate_rsa_keys.py
====================
Generates an RSA-2048 keypair for JWT RS256 signing.

Usage:
    python scripts/generate_rsa_keys.py                  # print .env snippet
    python scripts/generate_rsa_keys.py --write-env      # append to .env
    python scripts/generate_rsa_keys.py --write-files    # write PEM files

The generated variables must be set in your .env:
    JWT_PRIVATE_KEY="<RSA private key PEM — multi-line, quote the whole value>"
    JWT_PUBLIC_KEY="<RSA public key PEM — multi-line, quote the whole value>"
"""

import argparse
import sys
from pathlib import Path

# ─── Optional dependency guard ──────────────────────────────────────────────
try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa
    from cryptography.hazmat.backends import default_backend
except ImportError:
    print(
        "ERROR: 'cryptography' package not installed.\n"
        "Install with:  pip install cryptography\n"
        "It is already listed in pyproject.toml as a dependency.",
        file=sys.stderr,
    )
    sys.exit(1)


def generate_rsa_keypair(key_size: int = 2048) -> tuple[str, str]:
    """Return (private_key_pem, public_key_pem) as utf-8 strings."""
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=key_size,
        backend=default_backend(),
    )
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.TraditionalOpenSSL,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("utf-8")

    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode("utf-8")

    return private_pem, public_pem


def format_env_value(pem: str) -> str:
    """Convert a PEM string into a single-line .env-compatible value."""
    # Replace literal newlines with \\n so the env file remains one line per var
    return pem.replace("\n", "\\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate RSA-2048 keypair for JWT RS256",
    )
    parser.add_argument(
        "--key-size",
        type=int,
        default=2048,
        choices=[2048, 4096],
        help="RSA key size in bits (default: 2048)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--write-env",
        action="store_true",
        help="Append JWT_PRIVATE_KEY / JWT_PUBLIC_KEY to .env in project root",
    )
    mode.add_argument(
        "--write-files",
        action="store_true",
        help="Write jwt_private.pem and jwt_public.pem to scripts/ directory",
    )
    args = parser.parse_args()

    print(f"Generating RSA-{args.key_size} keypair …", flush=True)
    private_pem, public_pem = generate_rsa_keypair(key_size=args.key_size)

    if args.write_files:
        out_dir = Path(__file__).parent
        priv_path = out_dir / "jwt_private.pem"
        pub_path = out_dir / "jwt_public.pem"
        priv_path.write_text(private_pem)
        pub_path.write_text(public_pem)
        priv_path.chmod(0o600)  # owner read-only
        print(f"✅  Private key → {priv_path}  (chmod 600)")
        print(f"✅  Public key  → {pub_path}")
        print()
        print("⚠️  NEVER commit jwt_private.pem to git!")
        print("   Add to .gitignore:  scripts/jwt_private.pem")
        return

    private_env = format_env_value(private_pem)
    public_env = format_env_value(public_pem)

    env_block = (
        "\n# ── JWT RS256 keys (generated by scripts/generate_rsa_keys.py) ──\n"
        f'JWT_PRIVATE_KEY="{private_env}"\n'
        f'JWT_PUBLIC_KEY="{public_env}"\n'
        "JWT_ALGORITHM=RS256\n"
    )

    if args.write_env:
        env_file = Path(__file__).parent.parent / ".env"
        with env_file.open("a") as f:
            f.write(env_block)
        print(f"✅  Keys appended to {env_file}")
        print()
        print("⚠️  Verify .env is in .gitignore before committing!")
    else:
        # Print mode (default) — show snippet to copy/paste
        print("\n" + "=" * 70)
        print(" Copy the block below into your .env file")
        print("=" * 70)
        print(env_block)
        print("=" * 70)
        print("\nOr run with --write-env to append automatically.")
        print("Or run with --write-files to get jwt_private.pem / jwt_public.pem.\n")


if __name__ == "__main__":
    main()
